M48
; DRILL file {KiCad 9.0.9} date 2026-10-02T06:36:33+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-02T06:36:33+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X116.61Y-106.8
X122.39Y-106.8
T2
X148.5Y-139.5
M30
