M48
; DRILL file {KiCad 9.0.9} date 2026-10-01T08:07:21+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-01T08:07:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X182.4Y-129.61
X182.4Y-135.39
T2
X118.7Y-145.4
T3
X103.5Y-103.5
X162.5Y-166.0
X186.5Y-103.5
M30
